/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Trapezoid copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Line: typeof import('./src/components/Line.vue')['default']
    Linear: typeof import('./src/components/Linear.vue')['default']
    PointCloud: typeof import('./src/components/PointCloud.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rpc: typeof import('./src/components/Rpc.vue')['default']
    ThreeScene: typeof import('./src/components/ThreeScene.vue')['default']
    Trapezoid: typeof import('./src/components/Trapezoid.vue')['default']
    Trapezoid1: typeof import('./src/components/Trapezoid1.vue')['default']
    Trapezoid2: typeof import('./src/components/Trapezoid2.vue')['default']
    Trapezoid3: typeof import('./src/components/Trapezoid3.vue')['default']
    Trapezoid4: typeof import('./src/components/Trapezoid4.vue')['default']
    Trapezoid5: typeof import('./src/components/Trapezoid5.vue')['default']
    Trapezoid6: typeof import('./src/components/Trapezoid6.vue')['default']
  }
}
